name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        working-directory: ./src
        run: dotnet build --configuration Release /p:ContinuousIntegrationBuild=true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=./src/CanaryOverflow.sln --sarif-file-output=snyk.sarif

      - name: Upload snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
